// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL) {
  throw new Error(
    'Missing VITE_SUPABASE_URL environment variable. ' +
    'Please set it in your .env file or Vercel environment variables.'
  );
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing VITE_SUPABASE_ANON_KEY environment variable. ' +
    'Please set it in your .env file or Vercel environment variables.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Prevent automatic session detection from URL
  },
  global: {
    // Global error handler for auth errors
    headers: {
      'X-Client-Info': 'lingualab-web',
    },
  },
});

// Global error handler for refresh token errors and AbortErrors
// This catches errors that occur during automatic token refresh
if (typeof window !== 'undefined') {
  // Listen for unhandled promise rejections (refresh token errors)
  window.addEventListener('unhandledrejection', (event) => {
    const error = event.reason;
    
    // Ignore AbortError - it's usually caused by component unmounting or navigation
    // These are expected and don't need to be logged or handled
    if (error?.name === 'AbortError' || error?.message?.includes('aborted') || error?.message?.includes('signal is aborted')) {
      // Silently ignore AbortErrors - they're expected during navigation/unmounting
      event.preventDefault();
      return;
    }
    
    if (error?.message?.includes('Refresh Token') || 
        error?.message?.includes('Invalid Refresh Token') ||
        error?.message?.includes('refresh_token_not_found') ||
        error?.message?.includes('Refresh Token Not Found')) {
      // Clear session and redirect to login
      console.warn('Refresh token invalid, signing out...');
      supabase.auth.signOut().catch(() => {
        // Clear all Supabase auth-related localStorage items
        const keysToRemove: string[] = [];
        for (let i = 0; i < localStorage.length; i++) {
          const key = localStorage.key(i);
          if (key && (key.includes('supabase.auth') || key.includes('sb-') && key.includes('-auth-token'))) {
            keysToRemove.push(key);
          }
        }
        keysToRemove.forEach(key => localStorage.removeItem(key));
      });
      // Prevent default error handling
      event.preventDefault();
    }
  });
}